FROM python:3.12-slim
WORKDIR /app
RUN pip install uv
COPY pyproject.toml uv.lock* ./
RUN uv sync --no-dev --frozen
COPY ragnar/ui ./ragnar/ui
EXPOSE 8501
CMD ["uv", "run", "streamlit", "run", "ragnar/ui/streamlit_app.py"]
