[project]
name = "ragnar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling[easyocr]>=2.114.0",
    "fastapi>=0.141.1",
    "fastembed>=0.8.0",
    "loguru>=0.7.3",
    "pre-commit>=4.6.0",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.18.0",
    "redis>=5.0",
    "sentence-transformers>=5.7.0",
    "uvicorn>=0.52.3",
]

[mypy]
explicit-package-bases = ["ragnar=./ragnar"]
